[workspace]
members = ["thread", "pool", "asyncwait", "primitive", "collections", "process", "syncs", "channel", "timer_examples", "parking_lot_examples", "crossbeam_examples", "rayon_examples", "tokio_examples", "special"]